version: "3.7"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - jaeger-example
  benchmark:
    build: 
      # context: benchmark
      # image: benchmark
      dockerfile: Dockerfile
    networks:
      - jaeger-example
    depends_on:
      - jaeger

networks:
  jaeger-example:
